// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *home → Navigation*
 */
export interface HomeDocumentDataNavigationItem {
  /**
   * Link field in *home → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * label field in *home → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

type HomeDocumentDataSlicesSlice =
  | FooterSlice
  | HeaderSlice
  | HousingsliderSlice
  | MainsliderSlice
  | CtademoSlice
  | PartnerSlice
  | FeaturefourSlice
  | HomebannerSlice
  | AlternateGridSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Site Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * OG Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<HomeDocumentDataNavigationItem>>;

  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = HomeDocument;

/**
 * Item in *AlternateGrid → Default → Primary → items*
 */
export interface AlternateGridSliceDefaultPrimaryItemsItem {
  /**
   * title field in *AlternateGrid → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Item in *AlternateGrid → Image Right → Primary → items*
 */
export interface AlternateGridSliceImageRightPrimaryItemsItem {
  /**
   * title field in *AlternateGrid → Image Right → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Image Right → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * lbtn field in *AlternateGrid → Image Right → Primary → items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.items[].lbtn
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lbtn: prismic.LinkField;
}

/**
 * Primary content in *AlternateGrid → Default → Primary*
 */
export interface AlternateGridSliceDefaultPrimary {
  /**
   * eyebrowHeadline field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: alternate_grid.default.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * items field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<AlternateGridSliceDefaultPrimaryItemsItem>
  >;

  /**
   * Featurebutton field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.featurebutton
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  featurebutton: prismic.LinkField;
}

/**
 * Default variation for AlternateGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AlternateGridSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *AlternateGrid → Image Right → Primary*
 */
export interface AlternateGridSliceImageRightPrimary {
  /**
   * eyebrowHeadline field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: alternate_grid.imageRight.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * items field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<AlternateGridSliceImageRightPrimaryItemsItem>
  >;

  /**
   * learnmorebtn field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.learnmorebtn
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  learnmorebtn: prismic.LinkField;
}

/**
 * Image Right variation for AlternateGrid Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<AlternateGridSliceImageRightPrimary>,
  never
>;

/**
 * Slice variation for *AlternateGrid*
 */
type AlternateGridSliceVariation =
  | AlternateGridSliceDefault
  | AlternateGridSliceImageRight;

/**
 * AlternateGrid Shared Slice
 *
 * - **API ID**: `alternate_grid`
 * - **Description**: AlternateGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSlice = prismic.SharedSlice<
  "alternate_grid",
  AlternateGridSliceVariation
>;

/**
 * Primary content in *Ctademo → Default → Primary*
 */
export interface CtademoSliceDefaultPrimary {
  /**
   * ctasmall field in *Ctademo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ctademo.default.primary.ctasmall
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ctasmall: prismic.KeyTextField;

  /**
   * ctalarge field in *Ctademo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ctademo.default.primary.ctalarge
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  ctalarge: prismic.RichTextField;

  /**
   * ctabtn field in *Ctademo → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: ctademo.default.primary.ctabtn
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  ctabtn: prismic.LinkField;
}

/**
 * Default variation for Ctademo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtademoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtademoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Ctademo*
 */
type CtademoSliceVariation = CtademoSliceDefault;

/**
 * Ctademo Shared Slice
 *
 * - **API ID**: `ctademo`
 * - **Description**: Ctademo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtademoSlice = prismic.SharedSlice<
  "ctademo",
  CtademoSliceVariation
>;

/**
 * Primary content in *Ctasection → Default → Primary*
 */
export interface CtasectionSliceDefaultPrimary {
  /**
   * smallheading field in *Ctasection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ctasection.default.primary.smallheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  smallheading: prismic.KeyTextField;

  /**
   * ctaheading field in *Ctasection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ctasection.default.primary.ctaheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  ctaheading: prismic.RichTextField;

  /**
   * Request Demo btn field in *Ctasection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: ctasection.default.primary.request_demo
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  request_demo: prismic.LinkField;
}

/**
 * Default variation for Ctasection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtasectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtasectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Ctasection*
 */
type CtasectionSliceVariation = CtasectionSliceDefault;

/**
 * Ctasection Shared Slice
 *
 * - **API ID**: `ctasection`
 * - **Description**: Ctasection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtasectionSlice = prismic.SharedSlice<
  "ctasection",
  CtasectionSliceVariation
>;

/**
 * Item in *Fcard → Default → Primary → fmaincard*
 */
export interface FcardSliceDefaultPrimaryFmaincardItem {
  /**
   * fimg field in *Fcard → Default → Primary → fmaincard*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fcard.default.primary.fmaincard[].fimg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fimg: prismic.ImageField<never>;

  /**
   * fcontent field in *Fcard → Default → Primary → fmaincard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fcard.default.primary.fmaincard[].fcontent
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  fcontent: prismic.KeyTextField;
}

/**
 * Primary content in *Fcard → Default → Primary*
 */
export interface FcardSliceDefaultPrimary {
  /**
   * fmaincard field in *Fcard → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: fcard.default.primary.fmaincard[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  fmaincard: prismic.GroupField<
    Simplify<FcardSliceDefaultPrimaryFmaincardItem>
  >;
}

/**
 * Default variation for Fcard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FcardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FcardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Fcard*
 */
type FcardSliceVariation = FcardSliceDefault;

/**
 * Fcard Shared Slice
 *
 * - **API ID**: `fcard`
 * - **Description**: Fcard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FcardSlice = prismic.SharedSlice<"fcard", FcardSliceVariation>;

/**
 * Item in *Featurefour → Default → Primary → Featurefourcard*
 */
export interface FeaturefourSliceDefaultPrimaryFeaturefourcardItem {
  /**
   * featurefourimg field in *Featurefour → Default → Primary → Featurefourcard*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featurefour.default.primary.featurefourcard[].featurefourimg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featurefourimg: prismic.ImageField<never>;

  /**
   * featurefourdes field in *Featurefour → Default → Primary → Featurefourcard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featurefour.default.primary.featurefourcard[].featurefourdes
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  featurefourdes: prismic.KeyTextField;
}

/**
 * Primary content in *Featurefour → Default → Primary*
 */
export interface FeaturefourSliceDefaultPrimary {
  /**
   * Featurefourcard field in *Featurefour → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featurefour.default.primary.featurefourcard[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  featurefourcard: prismic.GroupField<
    Simplify<FeaturefourSliceDefaultPrimaryFeaturefourcardItem>
  >;
}

/**
 * Default variation for Featurefour Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturefourSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturefourSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Featurefour*
 */
type FeaturefourSliceVariation = FeaturefourSliceDefault;

/**
 * Featurefour Shared Slice
 *
 * - **API ID**: `featurefour`
 * - **Description**: Featurefour
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturefourSlice = prismic.SharedSlice<
  "featurefour",
  FeaturefourSliceVariation
>;

/**
 * Item in *Footer → Default → Primary → footermenuitem*
 */
export interface FooterSliceDefaultPrimaryFootermenuitemItem {
  /**
   * footermenu field in *Footer → Default → Primary → footermenuitem*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.footermenuitem[].footermenu
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  footermenu: prismic.LinkField;
}

/**
 * Item in *Footer → Default → Primary → footerprivacy*
 */
export interface FooterSliceDefaultPrimaryFooterprivacyItem {
  /**
   * footerlinks field in *Footer → Default → Primary → footerprivacy*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.footerprivacy[].footerlinks
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  footerlinks: prismic.LinkField;
}

/**
 * Item in *Footer → Default → Primary → Socialmedialinks*
 */
export interface FooterSliceDefaultPrimarySocialmedialinksItem {
  /**
   * sociallinks field in *Footer → Default → Primary → Socialmedialinks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.socialmedialinks[].sociallinks
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sociallinks: prismic.LinkField;
}

/**
 * Item in *Footer → Default → Primary → footercopyright*
 */
export interface FooterSliceDefaultPrimaryFootercopyrightItem {
  /**
   * footercoyrighttext field in *Footer → Default → Primary → footercopyright*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.footercopyright[].footercoyrighttext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footercoyrighttext: prismic.KeyTextField;
}

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * footerlogo field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.footerlogo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footerlogo: prismic.ImageField<never>;

  /**
   * footercontact field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.footercontact
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  footercontact: prismic.LinkField;

  /**
   * footermenuitem field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.footermenuitem[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footermenuitem: prismic.GroupField<
    Simplify<FooterSliceDefaultPrimaryFootermenuitemItem>
  >;

  /**
   * footerprivacy field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.footerprivacy[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footerprivacy: prismic.GroupField<
    Simplify<FooterSliceDefaultPrimaryFooterprivacyItem>
  >;

  /**
   * Socialmedialinks field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.socialmedialinks[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socialmedialinks: prismic.GroupField<
    Simplify<FooterSliceDefaultPrimarySocialmedialinksItem>
  >;

  /**
   * footercopyright field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.footercopyright[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footercopyright: prismic.GroupField<
    Simplify<FooterSliceDefaultPrimaryFootercopyrightItem>
  >;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Item in *Header → Default → Primary → menuitem*
 */
export interface HeaderSliceDefaultPrimaryMenuitemItem {
  /**
   * menuname field in *Header → Default → Primary → menuitem*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.menuitem[].menuname
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  menuname: prismic.LinkField;
}

/**
 * Item in *Header → Default → Primary → sidemenu*
 */
export interface HeaderSliceDefaultPrimarySidemenuItem {
  /**
   * sideitem field in *Header → Default → Primary → sidemenu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.sidemenu[].sideitem
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sideitem: prismic.LinkField;
}

/**
 * Primary content in *Header → Default → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * logo field in *Header → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * menuitem field in *Header → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.menuitem[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menuitem: prismic.GroupField<Simplify<HeaderSliceDefaultPrimaryMenuitemItem>>;

  /**
   * sidemenu field in *Header → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.sidemenu[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sidemenu: prismic.GroupField<Simplify<HeaderSliceDefaultPrimarySidemenuItem>>;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Primary content in *Homebanner → Default → Primary*
 */
export interface HomebannerSliceDefaultPrimary {
  /**
   * Maincontent field in *Homebanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: mainbanner
   * - **API ID Path**: homebanner.default.primary.maincontent
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  maincontent: prismic.KeyTextField;
}

/**
 * Default variation for Homebanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomebannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomebannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Homebanner*
 */
type HomebannerSliceVariation = HomebannerSliceDefault;

/**
 * Homebanner Shared Slice
 *
 * - **API ID**: `homebanner`
 * - **Description**: Homebanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomebannerSlice = prismic.SharedSlice<
  "homebanner",
  HomebannerSliceVariation
>;

/**
 * Item in *Housingslider → Default → Primary → housingcard*
 */
export interface HousingsliderSliceDefaultPrimaryHousingcardItem {
  /**
   * housingheading field in *Housingslider → Default → Primary → housingcard*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: housingslider.default.primary.housingcard[].housingheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  housingheading: prismic.RichTextField;

  /**
   * housingdes field in *Housingslider → Default → Primary → housingcard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: housingslider.default.primary.housingcard[].housingdes
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  housingdes: prismic.KeyTextField;

  /**
   * comingsoon field in *Housingslider → Default → Primary → housingcard*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: housingslider.default.primary.housingcard[].comingsoon
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  comingsoon: prismic.LinkField;
}

/**
 * Primary content in *Housingslider → Default → Primary*
 */
export interface HousingsliderSliceDefaultPrimary {
  /**
   * housingcard field in *Housingslider → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: housingslider.default.primary.housingcard[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  housingcard: prismic.GroupField<
    Simplify<HousingsliderSliceDefaultPrimaryHousingcardItem>
  >;
}

/**
 * Default variation for Housingslider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HousingsliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HousingsliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Housingslider*
 */
type HousingsliderSliceVariation = HousingsliderSliceDefault;

/**
 * Housingslider Shared Slice
 *
 * - **API ID**: `housingslider`
 * - **Description**: Housingslider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HousingsliderSlice = prismic.SharedSlice<
  "housingslider",
  HousingsliderSliceVariation
>;

/**
 * Primary content in *Mainslider → Default → Primary*
 */
export interface MainsliderSliceDefaultPrimary {
  /**
   * bannerimg field in *Mainslider → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mainslider.default.primary.bannerimg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bannerimg: prismic.ImageField<never>;

  /**
   * banner2 field in *Mainslider → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mainslider.default.primary.banner2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner2: prismic.ImageField<never>;

  /**
   * banner3 field in *Mainslider → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mainslider.default.primary.banner3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner3: prismic.ImageField<never>;
}

/**
 * Default variation for Mainslider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainsliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MainsliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Mainslider*
 */
type MainsliderSliceVariation = MainsliderSliceDefault;

/**
 * Mainslider Shared Slice
 *
 * - **API ID**: `mainslider`
 * - **Description**: Mainslider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainsliderSlice = prismic.SharedSlice<
  "mainslider",
  MainsliderSliceVariation
>;

/**
 * Item in *Onterogrid → Default → Primary → onteroheadings*
 */
export interface OnterogridSliceDefaultPrimaryOnteroheadingItem {
  /**
   * gridheadings field in *Onterogrid → Default → Primary → onteroheadings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: onterogrid.default.primary.onteroheading[].gridheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  gridheading: prismic.RichTextField;

  /**
   * griddescrption field in *Onterogrid → Default → Primary → onteroheadings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: onterogrid.default.primary.onteroheading[].griddes
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  griddes: prismic.KeyTextField;

  /**
   * gridlinks field in *Onterogrid → Default → Primary → onteroheadings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: onterogrid.default.primary.onteroheading[].gridlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  gridlink: prismic.LinkField;
}

/**
 * Primary content in *Onterogrid → Default → Primary*
 */
export interface OnterogridSliceDefaultPrimary {
  /**
   * onteroheadings field in *Onterogrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: onterogrid.default.primary.onteroheading[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  onteroheading: prismic.GroupField<
    Simplify<OnterogridSliceDefaultPrimaryOnteroheadingItem>
  >;
}

/**
 * Default variation for Onterogrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OnterogridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OnterogridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Onterogrid*
 */
type OnterogridSliceVariation = OnterogridSliceDefault;

/**
 * Onterogrid Shared Slice
 *
 * - **API ID**: `onterogrid`
 * - **Description**: Onterogrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OnterogridSlice = prismic.SharedSlice<
  "onterogrid",
  OnterogridSliceVariation
>;

/**
 * Primary content in *Partner → Default → Primary*
 */
export interface PartnerSliceDefaultPrimary {
  /**
   * Partnermainheading field in *Partner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner.default.primary.partnermainheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  partnermainheading: prismic.RichTextField;

  /**
   * partnerImg field in *Partner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partner.default.primary.partnerimg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  partnerimg: prismic.ImageField<never>;

  /**
   * Partnerheading field in *Partner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner.default.primary.partnerheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  partnerheading: prismic.RichTextField;

  /**
   * partnerdes field in *Partner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner.default.primary.partnerdes
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  partnerdes: prismic.KeyTextField;
}

/**
 * Default variation for Partner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Partner*
 */
type PartnerSliceVariation = PartnerSliceDefault;

/**
 * Partner Shared Slice
 *
 * - **API ID**: `partner`
 * - **Description**: Partner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnerSlice = prismic.SharedSlice<
  "partner",
  PartnerSliceVariation
>;

/**
 * Default variation for Slider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Slider*
 */
type SliderSliceVariation = SliderSliceDefault;

/**
 * Slider Shared Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Slider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSlice = prismic.SharedSlice<"slider", SliderSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataNavigationItem,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      AlternateGridSlice,
      AlternateGridSliceDefaultPrimaryItemsItem,
      AlternateGridSliceDefaultPrimary,
      AlternateGridSliceImageRightPrimaryItemsItem,
      AlternateGridSliceImageRightPrimary,
      AlternateGridSliceVariation,
      AlternateGridSliceDefault,
      AlternateGridSliceImageRight,
      CtademoSlice,
      CtademoSliceDefaultPrimary,
      CtademoSliceVariation,
      CtademoSliceDefault,
      CtasectionSlice,
      CtasectionSliceDefaultPrimary,
      CtasectionSliceVariation,
      CtasectionSliceDefault,
      FcardSlice,
      FcardSliceDefaultPrimaryFmaincardItem,
      FcardSliceDefaultPrimary,
      FcardSliceVariation,
      FcardSliceDefault,
      FeaturefourSlice,
      FeaturefourSliceDefaultPrimaryFeaturefourcardItem,
      FeaturefourSliceDefaultPrimary,
      FeaturefourSliceVariation,
      FeaturefourSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimaryFootermenuitemItem,
      FooterSliceDefaultPrimaryFooterprivacyItem,
      FooterSliceDefaultPrimarySocialmedialinksItem,
      FooterSliceDefaultPrimaryFootercopyrightItem,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeaderSlice,
      HeaderSliceDefaultPrimaryMenuitemItem,
      HeaderSliceDefaultPrimarySidemenuItem,
      HeaderSliceDefaultPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      HomebannerSlice,
      HomebannerSliceDefaultPrimary,
      HomebannerSliceVariation,
      HomebannerSliceDefault,
      HousingsliderSlice,
      HousingsliderSliceDefaultPrimaryHousingcardItem,
      HousingsliderSliceDefaultPrimary,
      HousingsliderSliceVariation,
      HousingsliderSliceDefault,
      MainsliderSlice,
      MainsliderSliceDefaultPrimary,
      MainsliderSliceVariation,
      MainsliderSliceDefault,
      OnterogridSlice,
      OnterogridSliceDefaultPrimaryOnteroheadingItem,
      OnterogridSliceDefaultPrimary,
      OnterogridSliceVariation,
      OnterogridSliceDefault,
      PartnerSlice,
      PartnerSliceDefaultPrimary,
      PartnerSliceVariation,
      PartnerSliceDefault,
      SliderSlice,
      SliderSliceVariation,
      SliderSliceDefault,
    };
  }
}
