// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *home → Navigation*
 */
export interface HomeDocumentDataNavigationItem {
  /**
   * Link field in *home → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * label field in *home → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

type HomeDocumentDataSlicesSlice =
  | FeaturedpointsSlice
  | HomebannerSlice
  | FeaturedSlice
  | AlternateGridSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Site Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * OG Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<HomeDocumentDataNavigationItem>>;

  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = HomeDocument;

/**
 * Item in *AlternateGrid → Default → Primary → items*
 */
export interface AlternateGridSliceDefaultPrimaryItemsItem {
  /**
   * title field in *AlternateGrid → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Item in *AlternateGrid → Image Right → Primary → items*
 */
export interface AlternateGridSliceImageRightPrimaryItemsItem {
  /**
   * title field in *AlternateGrid → Image Right → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Image Right → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *AlternateGrid → Default → Primary*
 */
export interface AlternateGridSliceDefaultPrimary {
  /**
   * eyebrowHeadline field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: alternate_grid.default.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * items field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<AlternateGridSliceDefaultPrimaryItemsItem>
  >;

  /**
   * Featurebutton field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.featurebutton
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  featurebutton: prismic.LinkField;
}

/**
 * Default variation for AlternateGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AlternateGridSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *AlternateGrid → Image Right → Primary*
 */
export interface AlternateGridSliceImageRightPrimary {
  /**
   * eyebrowHeadline field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: alternate_grid.imageRight.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * items field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<AlternateGridSliceImageRightPrimaryItemsItem>
  >;
}

/**
 * Image Right variation for AlternateGrid Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<AlternateGridSliceImageRightPrimary>,
  never
>;

/**
 * Slice variation for *AlternateGrid*
 */
type AlternateGridSliceVariation =
  | AlternateGridSliceDefault
  | AlternateGridSliceImageRight;

/**
 * AlternateGrid Shared Slice
 *
 * - **API ID**: `alternate_grid`
 * - **Description**: AlternateGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSlice = prismic.SharedSlice<
  "alternate_grid",
  AlternateGridSliceVariation
>;

/**
 * Primary content in *Featured → Default → Primary*
 */
export interface FeaturedSliceDefaultPrimary {
  /**
   * Featurelist field in *Featured → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured.default.primary.featurelist
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featurelist: prismic.RichTextField;
}

/**
 * Default variation for Featured Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Featured*
 */
type FeaturedSliceVariation = FeaturedSliceDefault;

/**
 * Featured Shared Slice
 *
 * - **API ID**: `featured`
 * - **Description**: Featured
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedSlice = prismic.SharedSlice<
  "featured",
  FeaturedSliceVariation
>;

/**
 * Item in *Featuredpoints → Default → Primary → featuredcard*
 */
export interface FeaturedpointsSliceDefaultPrimaryFeaturedcardItem {}

/**
 * Item in *Featuredpoints → featuredone → Primary → featuredcard*
 */
export interface FeaturedpointsSliceFeaturedonePrimaryFeaturedcardItem {}

/**
 * Item in *Featuredpoints → featuredtwo → Primary → featuredcard*
 */
export interface FeaturedpointsSliceFeaturedtwoPrimaryFeaturedcardItem {}

/**
 * Primary content in *Featuredpoints → Default → Primary*
 */
export interface FeaturedpointsSliceDefaultPrimary {
  /**
   * featuredcard field in *Featuredpoints → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredpoints.default.primary.featuredcard[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  featuredcard: prismic.GroupField<
    Simplify<FeaturedpointsSliceDefaultPrimaryFeaturedcardItem>
  >;

  /**
   * featuredimg field in *Featuredpoints → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredpoints.default.primary.featuredimg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featuredimg: prismic.ImageField<never>;

  /**
   * featuredheading field in *Featuredpoints → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredpoints.default.primary.featuredheadingmain
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featuredheadingmain: prismic.RichTextField;

  /**
   * featureddes field in *Featuredpoints → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredpoints.default.primary.featuredheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  featuredheading: prismic.KeyTextField;
}

/**
 * Default variation for Featuredpoints Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedpointsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedpointsSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Featuredpoints → featuredone → Primary*
 */
export interface FeaturedpointsSliceFeaturedonePrimary {
  /**
   * featuredcard field in *Featuredpoints → featuredone → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredpoints.featuredone.primary.featuredcard[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  featuredcard: prismic.GroupField<
    Simplify<FeaturedpointsSliceFeaturedonePrimaryFeaturedcardItem>
  >;

  /**
   * featuredimg field in *Featuredpoints → featuredone → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredpoints.featuredone.primary.featuredimg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featuredimg: prismic.ImageField<never>;

  /**
   * featuredheading field in *Featuredpoints → featuredone → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredpoints.featuredone.primary.featuredheadingmain
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featuredheadingmain: prismic.RichTextField;

  /**
   * featureddes field in *Featuredpoints → featuredone → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredpoints.featuredone.primary.featuredheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  featuredheading: prismic.KeyTextField;
}

/**
 * featuredone variation for Featuredpoints Slice
 *
 * - **API ID**: `featuredone`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedpointsSliceFeaturedone = prismic.SharedSliceVariation<
  "featuredone",
  Simplify<FeaturedpointsSliceFeaturedonePrimary>,
  never
>;

/**
 * Primary content in *Featuredpoints → featuredtwo → Primary*
 */
export interface FeaturedpointsSliceFeaturedtwoPrimary {
  /**
   * featuredcard field in *Featuredpoints → featuredtwo → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredpoints.featuredtwo.primary.featuredcard[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  featuredcard: prismic.GroupField<
    Simplify<FeaturedpointsSliceFeaturedtwoPrimaryFeaturedcardItem>
  >;

  /**
   * featuredimg field in *Featuredpoints → featuredtwo → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredpoints.featuredtwo.primary.featuredimg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featuredimg: prismic.ImageField<never>;

  /**
   * featuredheading field in *Featuredpoints → featuredtwo → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredpoints.featuredtwo.primary.featuredheadingmain
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featuredheadingmain: prismic.RichTextField;

  /**
   * featureddes field in *Featuredpoints → featuredtwo → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredpoints.featuredtwo.primary.featuredheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  featuredheading: prismic.KeyTextField;
}

/**
 * featuredtwo variation for Featuredpoints Slice
 *
 * - **API ID**: `featuredtwo`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedpointsSliceFeaturedtwo = prismic.SharedSliceVariation<
  "featuredtwo",
  Simplify<FeaturedpointsSliceFeaturedtwoPrimary>,
  never
>;

/**
 * Slice variation for *Featuredpoints*
 */
type FeaturedpointsSliceVariation =
  | FeaturedpointsSliceDefault
  | FeaturedpointsSliceFeaturedone
  | FeaturedpointsSliceFeaturedtwo;

/**
 * Featuredpoints Shared Slice
 *
 * - **API ID**: `featuredpoints`
 * - **Description**: Featuredpoints
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedpointsSlice = prismic.SharedSlice<
  "featuredpoints",
  FeaturedpointsSliceVariation
>;

/**
 * Primary content in *Features → Default → Primary*
 */
export interface FeaturesSliceDefaultPrimary {
  /**
   * Featurelist field in *Features → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.featurelist
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featurelist: prismic.RichTextField;
}

/**
 * Default variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Features*
 */
type FeaturesSliceVariation = FeaturesSliceDefault;

/**
 * Features Shared Slice
 *
 * - **API ID**: `features`
 * - **Description**: Features
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSlice = prismic.SharedSlice<
  "features",
  FeaturesSliceVariation
>;

/**
 * Primary content in *Homebanner → Default → Primary*
 */
export interface HomebannerSliceDefaultPrimary {
  /**
   * Maincontent field in *Homebanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: mainbanner
   * - **API ID Path**: homebanner.default.primary.maincontent
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  maincontent: prismic.KeyTextField;
}

/**
 * Default variation for Homebanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomebannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomebannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Homebanner*
 */
type HomebannerSliceVariation = HomebannerSliceDefault;

/**
 * Homebanner Shared Slice
 *
 * - **API ID**: `homebanner`
 * - **Description**: Homebanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomebannerSlice = prismic.SharedSlice<
  "homebanner",
  HomebannerSliceVariation
>;

/**
 * Default variation for Slider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Slider*
 */
type SliderSliceVariation = SliderSliceDefault;

/**
 * Slider Shared Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Slider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSlice = prismic.SharedSlice<"slider", SliderSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataNavigationItem,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      AlternateGridSlice,
      AlternateGridSliceDefaultPrimaryItemsItem,
      AlternateGridSliceDefaultPrimary,
      AlternateGridSliceImageRightPrimaryItemsItem,
      AlternateGridSliceImageRightPrimary,
      AlternateGridSliceVariation,
      AlternateGridSliceDefault,
      AlternateGridSliceImageRight,
      FeaturedSlice,
      FeaturedSliceDefaultPrimary,
      FeaturedSliceVariation,
      FeaturedSliceDefault,
      FeaturedpointsSlice,
      FeaturedpointsSliceDefaultPrimaryFeaturedcardItem,
      FeaturedpointsSliceDefaultPrimary,
      FeaturedpointsSliceFeaturedonePrimaryFeaturedcardItem,
      FeaturedpointsSliceFeaturedonePrimary,
      FeaturedpointsSliceFeaturedtwoPrimaryFeaturedcardItem,
      FeaturedpointsSliceFeaturedtwoPrimary,
      FeaturedpointsSliceVariation,
      FeaturedpointsSliceDefault,
      FeaturedpointsSliceFeaturedone,
      FeaturedpointsSliceFeaturedtwo,
      FeaturesSlice,
      FeaturesSliceDefaultPrimary,
      FeaturesSliceVariation,
      FeaturesSliceDefault,
      HomebannerSlice,
      HomebannerSliceDefaultPrimary,
      HomebannerSliceVariation,
      HomebannerSliceDefault,
      SliderSlice,
      SliderSliceVariation,
      SliderSliceDefault,
    };
  }
}
