// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid"),{ssr: false}),
  featured: dynamic(() => import("./Featured"),{ssr: false}),
  features: dynamic(() => import("./Features"),{ssr: false}),
  homebanner: dynamic(() => import("./Homebanner"),{ssr: false}),
  slider: dynamic(() => import("./Slider"),{ssr: false}),
};
