// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid"),{ssr: false}), 
  ctademo: dynamic(() => import("./Ctademo"),{ssr: false}), 
  ctasection: dynamic(() => import("./Ctasection"),{ssr: false}), 
  fcard: dynamic(() => import("./Fcard"),{ssr: false}), 
  featurefour: dynamic(() => import("./Featurefour"),{ssr: false}), 
  footer: dynamic(() => import("./Footer"),{ssr: false}), 
  header: dynamic(() => import("./Header"),{ssr: false}), 
  homebanner: dynamic(() => import("./Homebanner"),{ssr: false}), 
  housingslider: dynamic(() => import("./Housingslider"),{ssr: false}), 
  left_img: dynamic(() => import("./LeftImg"),{ssr: false}), 
  mainslider: dynamic(() => import("./Mainslider"),{ssr: false}), 
  onterogrid: dynamic(() => import("./Onterogrid"),{ssr: false}), 
  partner: dynamic(() => import("./Partner"),{ssr: false}), 
  slider: dynamic(() => import("./Slider"),{ssr: false}),  
};
